name: DevSecOps Pipeline

on:
  push:
    branches: [ "main", "staging" ]

permissions:
  contents: write  # Crucial: Allows the pipeline to write/push code changes back to GitHub
  id-token: write  # Crucial: Allows keyless WIF login to GCP

jobs:
  # ==========================================
  # JOB 1: CODE QUALITY & LINTING CHECK
  # ==========================================
  lint:
    name: 1. Code Quality & Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Linter
        run: pip install flake8

      - name: Run Flake8 Code Linting
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  # ==========================================
  # JOB 2: BUILD & VULNERABILITY CHECK
  # ==========================================
  build-and-scan:
    name: 2. Container Build & Security Scan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Login to Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: asia-southeast2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build Application Image
        run: |
          docker build -t asia-southeast2-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/pso-image-repo/guestbook-web:${{ github.sha }} .
          docker tag asia-southeast2-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/pso-image-repo/guestbook-web:${{ github.sha }} asia-southeast2-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/pso-image-repo/guestbook-web:latest

      - name: Run Trivy Security Scan
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          image-ref: 'asia-southeast2-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/pso-image-repo/guestbook-web:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'

      - name: Push Verified Image to Registry
        run: |
          docker push asia-southeast2-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/pso-image-repo/guestbook-web:${{ github.sha }}
          docker push asia-southeast2-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/pso-image-repo/guestbook-web:latest

  # ==========================================
  # JOB 3: MERGING FROM STAGING BRANCH TO MAIN BRANCH
  # ==========================================
  auto-promote:
    name: 3. Auto-Promote Staging to Main
    runs-on: ubuntu-latest
    needs: build-and-scan
    # CONDITION: Only run this job if the push event happened on the 'staging' branch
    if: github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches full history so branches can merge cleanly

      - name: Automated Git Merge & Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Switch to main, merge staging into it, and push back to GitHub
          git checkout main
          git merge staging --no-ff -m "ci: automatically update using the verified the build from staging"
          git push origin main

  # ==========================================
  # JOB 4: DEPLOY TO CLOUD RUN
  # ==========================================
  deploy:
    name: 4. Deploy to Production (Cloud Run)
    runs-on: ubuntu-latest
    needs: build-and-scan
    # CONDITION: Only deploy if the current target branch is explicitly 'main' or 'staging'
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy to GCP Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: guestbook-web
          image: asia-southeast2-docker.pkg.dev/${{ steps.auth.outputs.project_id }}/pso-image-repo/guestbook-web:${{ github.sha }}
          region: asia-southeast2
          flags: '--allow-unauthenticated'
          env_vars: |
            MONGO_URI=${{ secrets.MONGO_URI }}